export const SIGN_IN = 'SIGN_IN';
export const TAB_STACK_NAVIGATOR = 'TAB_STACK_NAVIGATOR';
export const MAIN_TABS_NAVIGATOR = 'MAIN_TABS_NAVIGATOR';
export const INSPECTIONS_NAVIGATOR = 'INSPECTIONS_NAVIGATOR';
export const SCHEDULE_NAVIGATOR = 'SCHEDULE_NAVIGATOR';
export const TICKETS_NAVIGATOR = 'TICKETS_NAVIGATOR';
export const ACCOUNT_NAVIGATOR = 'ACCOUNT_NAVIGATOR';
export const INSPECTIONS_HOME = 'INSPECTIONS_HOME';
export const INSPECTIONS_FORM = 'INSPECTIONS_FORM';
export const INSPECTIONS_FORM_LIST = 'INSPECTIONS_FORM_LIST';
export const SCHEDULE_HOME = 'SCHEDULE_HOME';
export const TICKETS_HOME = 'TICKETS_HOME';
export const ACCOUNT_HOME = 'ACCOUNT_HOME';

export const SIGNATURE_MODAL = 'SIGNATURE_MODAL';
export const RATING_CHOICES_MODAL = 'RATING_CHOICES_MODAL';
